import "@/app/styles.css";
import { AppWrapper } from "@/context";

//export const metadata = {
//title: "Next.js",
//description: "Generated by Next.js",
//};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body>
        <AppWrapper>{children}</AppWrapper>
      </body>
    </html>
  );
}
