import "@/app/styles.css";
import { AuthProvider } from "@/auth/authContext";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <AuthProvider>
      <html lang="pt-BR">
        <body>{children}</body>
      </html>
    </AuthProvider>
  );
}
