services:
  postgres:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=contability
    volumes:
      - polls_pg_data:/bitnami/postgresql

volumes:
  polls_pg_data:
